server:
  port:8081
  
spring:
  datasource:
    url: jdbc:h2:new:sd2024
    username: sd2024
    password: sd2024
  jpa:
  show-sql: true
  opne-in-view: false
  hibernate:
    ddl-auto: create 
  properties:
    hipernate:
      foramt_sql: true
  h2: 
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
